### ISSUE TITLE
Add ability to Save/Load config

### ISSUE THREAD

**Issue by Jivaross** [Jivaross/W10-Configurator#15]
Add function to save tasks selected and inputs filled to a ini file and load file

(Can be a Menu toolbar)

**Comment by LordStewie** [comment]
Created a Menu item for import/export of ini files. Also created a "Help" menu item.
![File Menu ScreenShot](https://user-images.githubusercontent.com/3180713/100028408-df656d80-2dbc-11eb-811a-51fcc9530ad1.png)

![Help Menu ScreenShot](https://user-images.githubusercontent.com/3180713/100028418-eab89900-2dbc-11eb-9a47-e202a2378595.png)

**Comment by Jivaross** [comment]
👍
